---
title: "Canadian Federal Election"
author: "Geunchul Shin"
format: pdf
---
#Part 1

```{r}
#### Preamble ####
# Purpose: Get data on 2021 Canadian Federal election
# Author: Geunchul Shin
# Email: joey.shin@mail.utoronto.ca
# Github: (https://github.com/geunchulshin/Tutorial-1)
# Date: 9 January 2024
```

```{r}
#### Workspace setup ####
#install.packages("tidyverse")
#install.packages("janitor")

library(tidyverse)
library(janitor)
```

```{r}
simulated_elections_data <-
  tibble(
    riding = rep(c(1:338)),
    elected_party= sample(c('Liberal','Conservative','Bloc Québécois','New Democratic','Green'), 338, replace = TRUE)
  )
```

#Part 2

```{r}
raw_elections_data <-
  read_csv(
    file =
      "https://www.elections.ca/res/rep/off/ovr2021app/53/data_donnees/table_tableau11.csv",
    show_col_types = FALSE
  )

write_csv(x = raw_elections_data, file = "election.csv")
```

```{r}
cleaned_elections_data <-
  clean_names(raw_elections_data)
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  select(electoral_district_name_nom_de_circonscription, elected_candidate_candidat_elu)
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  rename(
    electoral_district_name = electoral_district_name_nom_de_circonscription,
    elected_candidate = elected_candidate_candidat_elu)
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  separate(
    col = elected_candidate,
    into = c("Other", "party"),
    sep = "/"
  ) |>
  select(-Other)
```

```{r}
cleaned_elections_data$party |>
  unique()
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  mutate(
    party =
      case_match(
        party,
        "Libéral" ~ "Liberal",
        "Conservateur" ~ "Conservative",
        "Bloc Québécois" ~ "Bloc Québécois",
        "NPD-Nouveau Parti démocratique" ~ "New Democratic",
        "Parti Vert" ~ "Green"
      )
  )
```

```{r}
cleaned_elections_data |>
  ggplot(aes(x=party)) + 
  geom_bar() +
  theme_minimal() +
  labs(x="Party", y="number of ridings")
```

